package file

// Signature is a file signature
type Signature struct {
	Name                string   `json:"name"`
	HeaderSeq           []byte   `json:"header_seq"`
	Ext                 string   `json:"ext"`
	MimeType            string   `json:"mime_type"`
	SupportedExtensions []string `json:"supported_extensions"`
}

// Signatures is a list of file signatures
var Signatures = []Signature{
	//image file types
	{
		Name:                "PNG",
		HeaderSeq:           []byte{0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A},
		Ext:                 "png",
		MimeType:            "image/png",
		SupportedExtensions: []string{"png"},
	},
	{
		Name:                "JPEG",
		HeaderSeq:           []byte{0xFF, 0xD8, 0xFF},
		Ext:                 "jpg",
		MimeType:            "image/jpeg",
		SupportedExtensions: []string{"jpg", "jpeg"},
	},
	{
		Name:                "GIF",
		HeaderSeq:           []byte{0x47, 0x49, 0x46, 0x38, 0x39, 0x61},
		Ext:                 "gif",
		MimeType:            "image/gif",
		SupportedExtensions: []string{"gif"},
	},
	{
		Name:                "BMP",
		HeaderSeq:           []byte{0x42, 0x4D},
		Ext:                 "bmp",
		MimeType:            "image/bmp",
		SupportedExtensions: []string{"bmp"},
	},
	{
		Name:                "WEBP",
		HeaderSeq:           []byte{0x52, 0x49, 0x46, 0x46, 0x00, 0x00, 0x00, 0x00, 0x57, 0x45, 0x42, 0x50},
		Ext:                 "webp",
		MimeType:            "image/webp",
		SupportedExtensions: []string{"webp"},
	},
	{
		Name:                "TIFF",
		HeaderSeq:           []byte{0x4D, 0x4D, 0x00, 0x2A},
		Ext:                 "tiff",
		MimeType:            "image/tiff",
		SupportedExtensions: []string{"tiff", "tif"},
	},
	//video file types
	{
		Name:                "AVI",
		HeaderSeq:           []byte{0x52, 0x49, 0x46, 0x46, 0x00, 0x00, 0x00, 0x00, 0x41, 0x56, 0x49, 0x20},
		Ext:                 "avi",
		MimeType:            "video/x-msvideo",
		SupportedExtensions: []string{"avi"},
	},
	{
		Name:                "FLV",
		HeaderSeq:           []byte{0x46, 0x4C, 0x56, 0x01},
		Ext:                 "flv",
		MimeType:            "video/x-flv",
		SupportedExtensions: []string{"flv"},
	},
	{
		Name:                "MKV",
		HeaderSeq:           []byte{0x1A, 0x45, 0xDF, 0xA3},
		Ext:                 "mkv",
		MimeType:            "video/x-matroska",
		SupportedExtensions: []string{"mkv"},
	},
	{
		Name:                "MPG",
		HeaderSeq:           []byte{0x00, 0x00, 0x01, 0xBA},
		Ext:                 "mpg",
		MimeType:            "video/mpeg",
		SupportedExtensions: []string{"mpg"},
	},
	{
		Name:                "MP4",
		HeaderSeq:           []byte{0x00, 0x00, 0x00, 0x18, 0x66, 0x74, 0x79, 0x70, 0x6D, 0x70, 0x34, 0x32},
		Ext:                 "mp4",
		MimeType:            "video/mp4",
		SupportedExtensions: []string{"mp4"},
	},
	{
		Name:                "WEBM",
		HeaderSeq:           []byte{0x1A, 0x45, 0xDF, 0xA3},
		Ext:                 "webm",
		MimeType:            "video/webm",
		SupportedExtensions: []string{"webm"},
	},
	{
		Name:                "OGG",
		HeaderSeq:           []byte{0x4F, 0x67, 0x67, 0x53},
		Ext:                 "ogg",
		MimeType:            "video/ogg",
		SupportedExtensions: []string{"ogg"},
	},
	{
		Name:                "OGV",
		HeaderSeq:           []byte{0x4F, 0x67, 0x67, 0x53},
		Ext:                 "ogv",
		MimeType:            "video/ogg",
		SupportedExtensions: []string{"ogv"},
	},
	{
		Name:                "OGA",
		HeaderSeq:           []byte{0x4F, 0x67, 0x67, 0x53},
		Ext:                 "oga",
		MimeType:            "video/ogg",
		SupportedExtensions: []string{"oga"},
	},
	{
		Name:                "OGX",
		HeaderSeq:           []byte{0x4F, 0x67, 0x67, 0x53},
		Ext:                 "ogx",
		MimeType:            "video/ogg",
		SupportedExtensions: []string{"ogx"},
	},
	{
		Name:                "M4V",
		HeaderSeq:           []byte{0x00, 0x00, 0x00, 0x18, 0x66, 0x74, 0x79, 0x70, 0x6D, 0x70, 0x34, 0x32},
		Ext:                 "m4v",
		MimeType:            "video/mp4",
		SupportedExtensions: []string{"m4v"},
	},
	{
		Name:                "M4A",
		HeaderSeq:           []byte{0x00, 0x00, 0x00, 0x18, 0x66, 0x74, 0x79, 0x70, 0x6D, 0x70, 0x34, 0x32},
		Ext:                 "m4a",
		MimeType:            "video/mp4",
		SupportedExtensions: []string{"m4a"},
	},
	{
		Name:                "MOV",
		HeaderSeq:           []byte{0x00, 0x00, 0x00, 0x18, 0x66, 0x74, 0x79, 0x70, 0x6D, 0x70, 0x34, 0x32},
		Ext:                 "mov",
		MimeType:            "video/mp4",
		SupportedExtensions: []string{"mov"},
	},
	//audio file types
	{
		Name:                "MP3",
		HeaderSeq:           []byte{0x49, 0x44, 0x33},
		Ext:                 "mp3",
		MimeType:            "audio/mpeg",
		SupportedExtensions: []string{"mp3"},
	},
	{
		Name:                "WAV",
		HeaderSeq:           []byte{0x52, 0x49, 0x46, 0x46, 0x00, 0x00, 0x00, 0x00, 0x57, 0x41, 0x56, 0x45},
		Ext:                 "wav",
		MimeType:            "audio/wav",
		SupportedExtensions: []string{"wav"},
	},
	{
		Name:                "FLAC",
		HeaderSeq:           []byte{0x66, 0x4C, 0x61, 0x43},
		Ext:                 "flac",
		MimeType:            "audio/flac",
		SupportedExtensions: []string{"flac"},
	},
	{
		Name:                "M4A",
		HeaderSeq:           []byte{0x4D, 0x34, 0x41, 0x20},
		Ext:                 "m4a",
		MimeType:            "audio/m4a",
		SupportedExtensions: []string{"m4a"},
	},
	{
		Name:                "M4B",
		HeaderSeq:           []byte{0x4D, 0x34, 0x41, 0x20},
		Ext:                 "m4b",
		MimeType:            "audio/m4b",
		SupportedExtensions: []string{"m4b"},
	},
	{
		Name:                "M4P",
		HeaderSeq:           []byte{0x4D, 0x34, 0x41, 0x20},
		Ext:                 "m4p",
		MimeType:            "audio/m4p",
		SupportedExtensions: []string{"m4p"},
	},
	{
		Name:                "M4R",
		HeaderSeq:           []byte{0x4D, 0x34, 0x41, 0x20},
		Ext:                 "m4r",
		MimeType:            "audio/m4r",
		SupportedExtensions: []string{"m4r"},
	},
	{
		Name:                "M4V",
		HeaderSeq:           []byte{0x4D, 0x34, 0x56, 0x20},
		Ext:                 "m4v",
		MimeType:            "audio/m4v",
		SupportedExtensions: []string{"m4v"},
	},
	{
		Name:                "3GP",
		HeaderSeq:           []byte{0x66, 0x74, 0x79, 0x70, 0x33, 0x67, 0x70},
		Ext:                 "3gp",
		MimeType:            "audio/3gp",
		SupportedExtensions: []string{"3gp"},
	},
	//compressed file types
	{
		Name:                "ZIP",
		HeaderSeq:           []byte{0x50, 0x4B, 0x03, 0x04},
		Ext:                 "zip",
		MimeType:            "application/zip",
		SupportedExtensions: []string{"zip"},
	},
	{
		Name:                "RAR",
		HeaderSeq:           []byte{0x52, 0x61, 0x72, 0x21, 0x1A, 0x07, 0x00},
		Ext:                 "rar",
		MimeType:            "application/x-rar-compressed",
		SupportedExtensions: []string{"rar"},
	},
	{
		Name:                "7Z",
		HeaderSeq:           []byte{0x37, 0x7A, 0xBC, 0xAF, 0x27, 0x1C},
		Ext:                 "7z",
		MimeType:            "application/x-7z-compressed",
		SupportedExtensions: []string{"7z"},
	},
	{
		Name:                "GZ",
		HeaderSeq:           []byte{0x1F, 0x8B, 0x08},
		Ext:                 "gz",
		MimeType:            "application/gzip",
		SupportedExtensions: []string{"gz"},
	},
	{
		Name:                "TAR",
		HeaderSeq:           []byte{0x75, 0x73, 0x74, 0x61, 0x72},
		Ext:                 "tar",
		MimeType:            "application/x-tar",
		SupportedExtensions: []string{"tar"},
	},
	{
		Name:                "BZ2",
		HeaderSeq:           []byte{0x42, 0x5A, 0x68},
		Ext:                 "bz2",
		MimeType:            "application/x-bzip2",
		SupportedExtensions: []string{"bz2"},
	},
	{
		Name:                "XZ",
		HeaderSeq:           []byte{0xFD, 0x37, 0x7A, 0x58, 0x5A, 0x00},
		Ext:                 "xz",
		MimeType:            "application/x-xz",
		SupportedExtensions: []string{"xz"},
	},
	//document files types
	{
		Name:                "Microsoft Word document",
		HeaderSeq:           []byte{0xD0, 0xCF, 0x11, 0xE0, 0xA1, 0xB1, 0x1A, 0xE1},
		Ext:                 ".doc",
		MimeType:            "application/msword",
		SupportedExtensions: []string{},
	},

	{
		Name:                "Microsoft Word Open XML document",
		HeaderSeq:           []byte{0x50, 0x4B, 0x03, 0x04},
		Ext:                 ".docx",
		MimeType:            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
		SupportedExtensions: []string{},
	},
	{
		Name:                "Portable Document Format file",
		HeaderSeq:           []byte{0x25, 0x50, 0x44, 0x46},
		Ext:                 ".pdf",
		MimeType:            "application/pdf",
		SupportedExtensions: []string{},
	},
	{
		Name:                "Microsoft Excel spreadsheet",
		HeaderSeq:           []byte{0xD0, 0xCF, 0x11, 0xE0, 0xA1, 0xB1, 0x1A, 0xE1},
		Ext:                 ".xls",
		MimeType:            "application/vnd.ms-excel",
		SupportedExtensions: []string{},
	},

	{
		Name:                "Microsoft Excel Open XML spreadsheet",
		HeaderSeq:           []byte{0x50, 0x4B, 0x03, 0x04},
		Ext:                 ".xlsx",
		MimeType:            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
		SupportedExtensions: []string{},
	},
	{
		Name:                "Microsoft PowerPoint presentation",
		HeaderSeq:           []byte{0xD0, 0xCF, 0x11, 0xE0, 0xA1, 0xB1, 0x1A, 0xE1},
		Ext:                 ".ppt",
		MimeType:            "application/vnd.ms-powerpoint",
		SupportedExtensions: []string{},
	},
	{
		Name:                "Microsoft PowerPoint Open XML presentation",
		HeaderSeq:           []byte{0x50, 0x4B, 0x03, 0x04},
		Ext:                 ".pptx",
		MimeType:            "application/vnd.openxmlformats-officedocument.presentationml.presentation",
		SupportedExtensions: []string{},
	},
	{
		Name:                "OpenOffice Writer document",
		HeaderSeq:           []byte{0x50, 0x4B, 0x03, 0x04},
		Ext:                 ".odt",
		MimeType:            "application/vnd.oasis.opendocument.text",
		SupportedExtensions: []string{},
	},
	{
		Name:                "OpenOffice Calc spreadsheet",
		HeaderSeq:           []byte{0x50, 0x4B, 0x03, 0x04},
		Ext:                 ".ods",
		MimeType:            "application/vnd.oasis.opendocument.spreadsheet",
		SupportedExtensions: []string{},
	},
	{
		Name:                "OpenOffice Impress presentation",
		HeaderSeq:           []byte{0x50, 0x4B, 0x03, 0x04},
		Ext:                 ".odp",
		MimeType:            "application/vnd.oasis.opendocument.presentation",
		SupportedExtensions: []string{},
	},
	//executable files types
	{
		Name:                "Windows executable",
		HeaderSeq:           []byte{0x4D, 0x5A},
		Ext:                 ".exe",
		MimeType:            "application/x-msdownload",
		SupportedExtensions: []string{},
	},
	{
		Name:                "Linux executable",
		HeaderSeq:           []byte{0x7F, 0x45, 0x4C, 0x46},
		Ext:                 ".elf",
		MimeType:            "application/x-executable",
		SupportedExtensions: []string{},
	},
	{
		Name:                "Mac OS executable",
		HeaderSeq:           []byte{0xCF, 0xFA, 0xED, 0xFE},
		Ext:                 ".mach-o",
		MimeType:            "application/x-executable",
		SupportedExtensions: []string{},
	},
	{
		Name:                "Java class file",
		HeaderSeq:           []byte{0xCA, 0xFE, 0xBA, 0xBE},
		Ext:                 ".class",
		MimeType:            "application/java-vm",
		SupportedExtensions: []string{},
	},
	{
		Name:                "Windows DLL",
		HeaderSeq:           []byte{0x4D, 0x5A},
		Ext:                 ".dll",
		MimeType:            "application/x-msdownload",
		SupportedExtensions: []string{},
	},
	{
		Name:                "Windows driver",
		HeaderSeq:           []byte{0x4D, 0x5A},
		Ext:                 ".sys",
		MimeType:            "application/x-msdownload",
		SupportedExtensions: []string{},
	},
	{
		Name:                "Windows font",
		HeaderSeq:           []byte{0x00, 0x01, 0x00, 0x00},
		Ext:                 ".fon",
		MimeType:            "application/x-font",
		SupportedExtensions: []string{},
	},
	{
		Name:                "Windows font",
		HeaderSeq:           []byte{0x00, 0x01, 0x00, 0x00},
		Ext:                 ".fnt",
		MimeType:            "application/x-font",
		SupportedExtensions: []string{},
	},
	{
		Name:                "Binary executable",
		HeaderSeq:           []byte{0x7F, 0x45, 0x4C, 0x46},
		Ext:                 ".bin",
		MimeType:            "application/octet-stream",
		SupportedExtensions: []string{},
	},
}
